@echo off
echo Копирую node.exe в папку проекта...
copy "D:\WorkAi\Работы\node.exe" "%~dp0node.exe" >nul 2>&1
echo Добавляю текущую папку и Node.js в PATH...
set PATH=%~dp0;%PATH%;D:\WorkAi\Работы
echo Запускаю npm install...
D:\WorkAi\Работы\npm.cmd install
